version: '3.1'

services:

  app:
    build: .
    ports:
      - "8002:8002"
    links:
      - "db:db"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=groupmanagement
